module.exports = {
  Villanova: {Radford: -23.5},
  'Virginia Tech': {Alabama: -2},
  'Rhode Island': {Oklahoma: -2},
  Duke: {Iona: -20.5},
  Kansas: {Pennsylvania: -14},
  'Seton Hall': {'NC State': -2.5},
  'Houston': {'San Diego State': -4},
  'Michigan': {Montana: -11},
  'Miami-Florida': {'Loyola Chicago': -1.5},
  Tennessee: {'Wright State': -12},
  Florida: {'St Bonaventure': -5.5},
  'Texas Tech': {'Stephen F. Austin': -11},
  Kentucky: {Davidson: -5},
  Arizona: {Buffalo: -8.5},
  'Ohio State': {'South Dakota State': -7.5},
  Gonzaga: {'NC Greensboro': -12.5},
  'Austin Peay': {'la-Monroe': -3.5},
  'Virginia': {'MD Baltimore CO': -21.5},
  Creighton: {'Kansas State': -1.5},
  'Texas A&M': {Providence: -3},
  'North Carolina': {Lipscomb: -19.5},
  Arkansas: {Butler: 1.5},
  Purdue: {'CS Fullerton': -20.5},
  'Michigan State': {Bucknell: -14.5},
  Nevada: {Texas: -1},
  Cincinnati: {'Georgia State': -14},
  Missouri: {'Florida State': 1.5},
  'West Virginia': {'Murray State': -10.5},
  'Wichita State': {Marshall: -11.5},
  Clemson: {'New Mexico State': -5},
  Auburn: {'Col Charleston': -9},
};
